### ISSUE TITLE
Change default export directory

### ISSUE THREAD

**Issue by jonschwenk** [jonschwenk/rabpro#38]
When I exported the basin shapefiles (`self.export('all')`), it defaulted to `c:\users\jon\results\name_of_run`. I think the exports should probably be in the appdirs folder as well, no? Either that or force the user to supply a directory to result outputs...

**Comment by tzussman** [comment]
I think the current behavior is to export results in the current working directory - that makes much more sense to me than exporting into the appdirs directory, since those should be infrequently accessed. However, users can overwrite this by passing a value to the `path_results` parameter in the profiler constructor
