### ISSUE TITLE
Including a geopackage layer of the MERIT grid

### ISSUE THREAD

**Issue by jsta** [jonschwenk/rabpro#56]
Then we could intersect a given "coords file" to figure out what data needs to be downloaded for a job.

The MERIT data is prepared as 5 degree x 5 degree tiles (6000 pixel x 6000 pixel) but it's packaged as 30 degree x 30 degree "megatiles". These megatile codes are the important piece of information needed to point to a specific data download.

![image](https://user-images.githubusercontent.com/7844578/130375192-22dede75-c5aa-46bc-80c4-8d9e1fb21dc3.png)

**Comment by jonschwenk** [comment]
We don't want to try to automate MERIT data fetching at this point. The problem is that we don't know how big of an area (or how many tiles, rather) is needed, since all we have is a outlet coordinate which could be e.g. for the entire Yukon Basin or just a tiny tributary near the Yukon mainstem. We decided to leave this up to the user.

**Comment by jsta** [comment]
Right, I'm not hoping to automate fetching, but I'm hoping to write a function that takes a coordinate pair as input and returns the associated merit tile code. Guess there's no need for a spatial layer for this...
